version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: campusflow_postgres
    restart: always
    environment:
      POSTGRES_USER: campusflow
      POSTGRES_PASSWORD: campusflow_password
      POSTGRES_DB: campusflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: campusflow_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://campusflow:campusflow_password@db:5432/campusflow_db
      SECRET_KEY: campusflow_docker_production_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campusflow_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
